# Use root/example as user/password credentials
version: '3'
name: mypost
services:
  mongo:
    container_name: db-mongo
    image: mongo:7
    ports:
      - '27027:27017'
    restart: on-failure
    expose:
      - 27027
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin123

  cache:
    container_name: myposts-cache
    image: redis:7
    ports:
      - '6379:6379'
    restart: on-failure
    expose:
      - 6379
    volumes:
      - ./redis:/data
